package com.yj.oa.project.service.user;

import com.yj.oa.project.po.User;

import java.util.List;

/**
 * @author 永健
 * @date $date$ $time$
 * @描述
 */
public interface IUserService {

    /**
     *
     * @描述:  login登录验证
     *
     * @params:
     * @return:
     * @date: 2018/9/29 21:50
     */
    User login(String uid);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     *
     * 根据Id主键查询单个用户 登录用此方法
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(String uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     * 更改用户
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);


    /*
     *
     * 批量删除用户
     *
     * */
    int deleteByPrimaryKeys(String[] ids) throws Exception;

    /*
     *
     * 用户列表 以及 根据条件查询
     *
     * */
    List<User> selectByUser(User user);



    /**
     * 校验手机号码是否唯一
     *
     * @param user 用户信息
     * @return 结果
     */
    String checkPhoneUnique(User user);

    /**
     * 校验email是否唯一
     *
     * @param user 用户信息
     * @return 结果
     */
    String checkEmailUnique(User user);


    /**
     *
     * @描述 修改密码
     *
     * @date 2018/9/16 10:34
     */
    int resrtPwd(User user);


    /**
     * 校验用户登录名是否唯一
     *
     * @param email 用户邮箱
     *
     * @return 结果
     */
    String checkLoginNameUnique(User user);

}
