package com.yj.oa.project.po;

import com.yj.oa.framework.web.po.BasePo;

public class RoleMenu extends BasePo{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_menu.rm_id
     *
     * @mbggenerated
     */
    private Integer rm_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_menu.role_ID
     *
     * @mbggenerated
     */
    private Integer role_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_menu.menuOne_id
     *
     * @mbggenerated
     */
    private Integer menuOne_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_menu.rm_id
     *
     * @return the value of t_role_menu.rm_id
     *
     * @mbggenerated
     */
    public Integer getRm_id() {
        return rm_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_menu.rm_id
     *
     * @param rm_id the value for t_role_menu.rm_id
     *
     * @mbggenerated
     */
    public void setRm_id(Integer rm_id) {
        this.rm_id = rm_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_menu.role_ID
     *
     * @return the value of t_role_menu.role_ID
     *
     * @mbggenerated
     */
    public Integer getRole_ID() {
        return role_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_menu.role_ID
     *
     * @param role_ID the value for t_role_menu.role_ID
     *
     * @mbggenerated
     */
    public void setRole_ID(Integer role_ID) {
        this.role_ID = role_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_menu.menuOne_id
     *
     * @return the value of t_role_menu.menuOne_id
     *
     * @mbggenerated
     */
    public Integer getMenuOne_id() {
        return menuOne_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_menu.menuOne_id
     *
     * @param menuOne_id the value for t_role_menu.menuOne_id
     *
     * @mbggenerated
     */
    public void setMenuOne_id(Integer menuOne_id) {
        this.menuOne_id = menuOne_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_menu
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rm_id=").append(rm_id);
        sb.append(", role_ID=").append(role_ID);
        sb.append(", menuOne_id=").append(menuOne_id);
        sb.append("]");
        return sb.toString();
    }
}